//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SvgToJwwConverter.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SvgToJwwConverter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   SVG to JWW Converter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Canceled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirmation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Converting...  {0}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Converting {
            get {
                return ResourceManager.GetString("Converting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Curve divisions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CurveDiv {
            get {
                return ResourceManager.GetString("CurveDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OnlyLine {
            get {
                return ResourceManager.GetString("OnlyLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Jww after conversion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenJww {
            get {
                return ResourceManager.GetString("OpenJww", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overwrite に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Overwrite {
            get {
                return ResourceManager.GetString("Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is already exist.\nOverwrite? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OverwriteConfirm {
            get {
                return ResourceManager.GetString("OverwriteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] template {
            get {
                object obj = ResourceManager.GetObject("template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Converts only strokes and does not convert fills. Strokes also show the outline of the fill. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_OnlyLine {
            get {
                return ResourceManager.GetString("Tooltip_OnlyLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   if checked, open Jw_cad after conversion. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_OpenJww {
            get {
                return ResourceManager.GetString("Tooltip_OpenJww", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If checked, it will overwrite without confirmation even if the same file name already exists. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_Overwrite {
            get {
                return ResourceManager.GetString("Tooltip_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click to open a file open dialog. Then select the SVG file to convert. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_SelectFile {
            get {
                return ResourceManager.GetString("Tooltip_SelectFile", resourceCulture);
            }
        }
    }
}
